<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ScytheButler.data\ScytheButler.data.csproj" />
    <ProjectReference Include="..\Dashboard.ServiceDefaults\Dashboard.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\components\" />
    <Folder Include="Services\" />
    <Folder Include="Resources\Images\Icons\" />
  </ItemGroup>

</Project>
